library("repo.data")
alias_columns <- c("Package", "Source", "Target")
pkges <- c("BaseSet", "experDesign")
# Test that cache works
st <- system.time(ca <- cran_alias(pkges))
repo.data:::no_internet(ca)
stopifnot(colnames(ca) == alias_columns)
st1 <- system.time(ca2 <- cran_alias(pkges))
stopifnot("Cache didn't work" = st1[[3]] < st[[3]])
stopifnot("Cache was not the same" = all.equal(ca, ca2))

clean_cache()
st2 <- system.time(ca3 <- cran_alias(pkges))
repo.data:::no_internet(ca3)
stopifnot("Clean cache restores initial" = st2[[3]] > st[[3]])
stopifnot("Still same result" = all.equal(ca, ca3))

ca <- cran_alias()
repo.data:::no_internet(ca)
stopifnot(colnames(ca) == alias_columns)
ca2 <- cran_alias()
stopifnot("Cache returns the same for all packages" = all.equal(ca, ca2))

st <- system.time(ba <- base_alias(pkges))
repo.data:::no_internet(ba)
stopifnot(colnames(ba) == alias_columns)
st1 <- system.time(ba2 <- base_alias(pkges))
stopifnot("Cache didn't work" = st1[[3]] < st[[3]])
stopifnot("Cache was not the same" = all.equal(ba, ba2))

clean_cache()
st2 <- system.time(ba3 <- base_alias(pkges))
repo.data:::no_internet(ba3)
stopifnot("Clean cache restores initial" = st2[[3]] > st[[3]])
stopifnot("Still same result" = all.equal(ba, ba3))

ba <- base_alias()
repo.data:::no_internet(ba)
stopifnot(colnames(ba) == alias_columns)
ba2 <- base_alias()
stopifnot("Cache returns the same for all packages" = all.equal(ba, ba2))


clean_cache()
a <- alias()
repo.data:::no_internet(a)
stopifnot(colnames(a) == alias_columns)
pkges <- c(pkges, "BioCor")

st <- system.time(ba <- alias(pkges))
repo.data:::no_internet(ba)
stopifnot(colnames(ba) == alias_columns)
st1 <- system.time(ba2 <- alias(pkges))
stopifnot("Cache didn't work" = st1[[3]] < st[[3]])
stopifnot("Cache was not the same" = all.equal(ba, ba2))

clean_cache()
st2 <- system.time(ba3 <- alias(pkges))
repo.data:::no_internet(ba3)
stopifnot("Clean cache restores initial" = st2[[3]] > st[[3]])
stopifnot("Still same result" = all.equal(ba, ba3))

ba <- alias()
repo.data:::no_internet(ba)
stopifnot(colnames(ba) == alias_columns)
ba2 <- alias()
stopifnot("Cache returns the same for all packages" = all.equal(ba, ba2))