library("repo.data")

ca <- cran_actions()
repo.data:::no_internet(ca)
stopifnot("Unexpected dimensions" = ncol(ca) == 6)
col_names <- c("Date", "Time", "User", "Action", "Package", "Version")
stopifnot("Unexpected column names" = colnames(ca) == col_names)
stopifnot(is(ca$Date, "Date"))
stopifnot(is(ca$Time, "character"))
stopifnot(is(ca$User, "factor"))
stopifnot(is(ca$Action, "factor"))
stopifnot("New action" = all(ca$Action %in% c("publish", "archive", "remove")))
stopifnot(is(ca$Package, "factor"))
stopifnot(is(ca$Version, "character"))

